In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/raw/multimedia.csv')
df.head()

,_id,license,title,format,rightsHolder,identifier,type
0,6763934,http://creativecommons.org/licenses/by/4.0/,NHMUK010361996_Yramea_cytheris_ cytheris_ (Dru...,image/jpeg,"The Trustees of the Natural History Museum, Lo...",https://www.nhm.ac.uk/services/media-store/ass...,StillImage
1,6763934,http://creativecommons.org/licenses/by/4.0/,NHMUK010361996_Yramea_cytheris_ cytheris_ (Dru...,image/jpeg,"The Trustees of the Natural History Museum, Lo...",https://www.nhm.ac.uk/services/media-store/ass...,StillImage
2,8738302,http://creativecommons.org/licenses/by/4.0/,013463487_137028_1083165,image/jpeg,"The Trustees of the Natural History Museum, Lo...",https://www.nhm.ac.uk/services/media-store/ass...,StillImage
3,8792648,http://creativecommons.org/licenses/by/4.0/,NHMUK010897581_E__f_fasciatus_dorsal_and_label...,image/jpeg,"The Trustees of the Natural History Museum, Lo...",https://www.nhm.ac.uk/services/media-store/ass...,StillImage
4,8792648,http://creativecommons.org/licenses/by/4.0/,NHMUK010897581_E__f_fasciatus_ventral_and_labe...,image/jpeg,"The Trustees of the Natural History Museum, Lo...",https://www.nhm.ac.uk/services/media-store/ass...,StillImage

In [3]:
df[['_id', 'identifier']].sample(n=10)

             _id                                         identifier
1171406  5627892  http://www.nhm.ac.uk/services/media-store/asse...
1101476  5617065  http://www.nhm.ac.uk/services/media-store/asse...
1002974  6874271  http://www.nhm.ac.uk/services/media-store/asse...
821267   6933337  http://www.nhm.ac.uk/services/media-store/asse...
659143   8077591  http://www.nhm.ac.uk/services/media-store/asse...
340162   7029803  http://www.nhm.ac.uk/services/media-store/asse...
253634   6930159  http://www.nhm.ac.uk/services/media-store/asse...
350270   6863866  http://www.nhm.ac.uk/services/media-store/asse...
367053   2992408  http://www.nhm.ac.uk/services/media-store/asse...
542332   5681637  http://www.nhm.ac.uk/services/media-store/asse...

In [4]:
import requests
import io
from PIL import Image

test_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Genkyuen02s3200.jpg/640px-Genkyuen02s3200.jpg'
r = requests.get(test_url)
image_bytes = io.BytesIO(r.content)
im = Image.open(image_bytes)
print(im)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=640x428 at 0x7F911FAE6240>